services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: mongod --replSet myReplicaSet --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./data1:/data/db
    networks:
      - mongo-network

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: mongod --replSet myReplicaSet --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - ./data2:/data/db
    networks:
      - mongo-network

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: mongod --replSet myReplicaSet --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - ./data3:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge